### ISSUE TITLE
Enchanting books usage in anvils (addition to Tutorial book)

### ISSUE THREAD

**Issue by Ghostlyfire99** [naturecraft-dev/naturecraft#103]
Whenever a stacked enchanted book is shift clicked into an anvil, it uses all of them.

I would like that a warning be put lets say, in the tutorial book of the effect of this.

People who actually read the tutorial book will be aware to not do this mistake and wont lose more of their time or essence.

No effect to game balance

**Comment by Barbadosian** [comment]
This is retiring along with the rest of stacking behavior (very soon)
