### ISSUE TITLE
[Feat] Rank Setup for Patrician and above

### ISSUE THREAD

**Issue by naturecraft-development** [naturecraft-dev/naturecraft#19]
- [ ] Use Quests/Achievement based requirements for killing special custom mobs and bosses.
- [ ] Set up NPCs for handing out Rankup Quests in the Hub's Quest section
- [ ] Set up perks and sync with group permissions.

**Comment by Barbadosian** [comment]
Personal ranks removed. Issue no longer relevant.

Thank you for your support in NatureCraft and we always appreciate your feedback.
