### ISSUE TITLE
[Feat] No more censorship!

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#21]
Submitted By:
No more censorship!

Feature Description:
Remove censorship plugin

Benefit to the entire server:
No more annoying "*****", No more normal words being censored

Effect on game balance:
It will not. However, I would keep some words banned like the n word, "faggot", "spick", etc.

Type Key:
[FEAT]

**Comment by naturecraft-development** [comment]
Under discussion. Accept response after more player data is gathered.

**Comment by benevolent2012** [comment]
Seems to be an effective way of keeping the chat clean.
