### ISSUE TITLE
[Wiki] The inception of Socialist Alaska and the SCR

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#22]
Submitted By:
thek1tten

Benefit to the entire server:
We were the first town, and the first nation on the server (other than Qin Dynasty, which was created by Barbados).

Type Key:
[DOCU]

**Comment by naturecraft-development** [comment]
What feature request is this? Please follow the format.

**Comment by Barbadosian** [comment]
Due to some error on the backend the title was displayed to be Feature instead of Wiki, therefore reopening the issue.

The wiki is free-to-edit for ANYONE as long as you register for an account. Please feel free to create page and write about your own nations and towns. If you are confident enough to write a wiki about commands also feel free to do so, and you can contact admins for rewards.

Please do not abuse wiki as it will be the source of knowledge for the server community.
