### ISSUE TITLE
[Feature] ElytraFlight Blocker

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#24]
Submitted By:
ElytraFlight Blocker

Feature Description:
Dark_Chrome and I have been testing ElytraFlight. It allows us a player to travel at extremely fast speeds (faster than the chunks load), and lowers server TPS

Benefit to the entire server:
Those with a modded client will no longer be able to travel across the world in 4 minutes. It will also keep the server stable

Effect on game balance:
..

Type Key:
[FEAT]

**Comment by naturecraft-development** [comment]
The blocker had been temporarily taken down for maintenance purposes. We have turned it back on. Please check and if the issue persists, let us know!

Thanks for actively letting us know :)
