### ISSUE TITLE
[Feature] /trash

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#38]
Submitted By:
thek1tten

Feature Description:
/trash command that opens an empty inventory. All items placed in it will be trashed

Benefit to the entire server:
Removes the need for a lava trash bin in one's house, and also reduces the number of players dumping hundreds of items (reduces lag)

Effect on game balance:
No

Type Key:
[FEAT]

**Comment by jiajunmao** [comment]
This feature seems nice to have, but it could be worked around by just building a simple redstone contraption with a chest and dispenser. Not adding.
