### ISSUE TITLE
[Feature] Staff Applications and Titles

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#40]
Submitted By:
LadyPepperIX

Feature Description:
Not needed too promptly, but as the server grows allow applications and in-game titles to those who are accepted. (Such as Helper, Mod, Wiki, Builder, etc.) And relevant titles in the Discord server.

Benefit to the entire server:
It would give people roles in the server to contribute as more than just members to give new players a greater experience and also have a more community-interactive server while also helping the devs by letting them focus on more important subjects outside of direct gameplay such as editing the code..

Effect on game balance:
This obviously doesn't have any direct effect on gameplay but allowing players to help the server by editing the wiki, configuring the Discord server, and providing assistance all improve players' experience of the server and help it grow to maintain an active and supportive community. Of course also build up trust and punish those who abuse their power.

Type Key:
[FEAT]

**Comment by naturecraft-development** [comment]
Staff have been recruited.
