### ISSUE TITLE
[Bug] Guardian flying across players' screens all the time

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#43]
Submitted By:
thek1tten again

Game Version/Launcher:
Every version the server supports

Bug Description:
New players are annoyed and confused by the guardian that flys around them every once in a while. I am annoyed by it, personally.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
Should be fixed. Reopen if the same issue is seen.
