### ISSUE TITLE
[Bug] /quest going to quest portal

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#45]
Submitted By:
tair0

Game Version/Launcher:
1.16.3, Badlion

Bug Description:
Every time I go to do /quest to learn about where I am on my quests, it just sends me to the warp instead.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
That is not a bug. To open your quest menu, use **/menu**.
We did that to simplify the quest commands.
