### ISSUE TITLE
[Feature] Ads the server on reddit

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#48]
Submitted By:
King_Of_Barbados

Feature Description:
Ading the server on reddit might draw more players onto the server since all the major minecraft server listings are dominated by the big name servers.

Benefit to the entire server:
get more players and grow a bigger community

Effect on game balance:
Nope.

Type Key:
[FEAT]

**Comment by jiajunmao** [comment]
done
