### ISSUE TITLE
[Feature] AFK Farms

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#49]
Submitted By:
3WM

Feature Description:
Plug in a bot that will afk only one chunk that you can buy for however much (probably pretty expensive)

Benefit to the entire server:
Afking a farm requires you to leave your computer on overnight, especially with a tower this can be very unhealthy for the computer and also be a good amount of expensive with the electricity bill

Effect on game balance:
It won’t affect it as much as it sounds, people can create afk pools as I did and afk it all night, I guess it could if you buy more than one of them so maybe one bot per person could make it more playable 

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
seems like a good feature to add on later on as we have more people 
Thoughts? @Barbadosian

**Comment by Barbadosian** [comment]
Thank you for you suggestion. It has been admitted to the server roadmap and will be released in the future.

**Comment by benevolent2012** [comment]
Not in Terra
