### ISSUE TITLE
[Bug] Town and nation will collapse

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#50]
Submitted By:
Reverse_______

Game Version/Launcher:
1.16.1, optifine

Bug Description:
In the economy adjustment the ICR and Alaska’s balance has been dropped by 2 zeroes, which is understandable given the fact that the economy needs to be adjusted, but in doing so, Alaska and the ICR are close to falling because of the lack of money, and we don’t have enough money to keep the ICR running. Is it possible for some of the money to be returned to the ICR and Alaska’s bank, so that the town and nation may keep running? I know this isn’t a bug, but 99% of that money was earned fairly by getting money from mob drops and mining(Normal mining), and for it to just be taken away is devastating to the nation and the town.

Type Key:
[BUG]

**Comment by jiajunmao** [comment]
Since ICR and Alaska are both disbanded at this point, this discussion is closed.
