### ISSUE TITLE
[Bug] Mushroom textures

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#53]
Submitted By:
Maulvath

Game Version/Launcher:
1.16.3 Vanilla

Bug Description:
Currently, several mushrooms (big ones) in the game, have wrong textures, which I assume is a problem with the ressource pack. If the mushroom blocs in question are broken, those around it turn back to the normal texture.
The following link is a screenshot showing the bug.
https://ibb.co/yN789nj

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
As far as I know, only mushrooms in Atlantis is affected (old generation of land, so our item data didn't quite match).
Do you have coordinates for mushrooms like that in other continents other than atlantis?
