### ISSUE TITLE
[Feature] Bonus claim cost

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#56]
Submitted By:
Maulvath

Feature Description:
I believe that the cost of bonus claims should be reduced. It currently cost Shima 1500 per new claim. While it is true that there NEEDS to be an increase in the prices of claim, Shima has only bought 50 out of the 1200 possible bonus claims. Which make the prices at higher level even more difficult to reach..

Benefit to the entire server:
It will allow active Towns to expend more easily by just playing and working for it. Without putting an increasingly hard bar that prevent normal gameplay and force a 100% focus on making money.

Effect on game balance:
It shouldn't either, rather it will relax Towns who seek to take a set territory, and give them better chances to reach their goal, rather than need months and months of farming.

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
A bonus claim costs 80. It is already very low.
Active towns should have no issues expanding whether through recruiting members (easiest way to double the number of claims) or buying bonus claims.
Check **/town** for your town level.

**Comment by benevolent2012** [comment]
@Barbadosian Should be 80. The modifiers doesn't seem to apply. Perhaps needs a restart.

**Comment by benevolent2012** [comment]
Fixed.
