### ISSUE TITLE
[Feature] Rebalance/Reintroduction of Nations

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#57]
Submitted By:
Maulvath

Feature Description:
While I fully understand the Staff's decision to remove nations for the time being, it has offered some problems that needs solution. As of now, Towns are drastically limited by this new rule; while they fail to impose the required need of 'single towns players' as it remains possible to use outpost for the same concept. A solution discussed on the discord, is to reduce the price of Nations and make them more affordable, ergo allowing nations to be more easily made, rather than being incorporated in super powers. An instance of the problems it cause occured today for Shima, a new player asked to Join, and while we do wish for new players, we would rather keep the Imperial Province (aka our main town) for people we directly know, and let other settle other areas of Japan that are still part of Shima. due to our current situation, we had to say no and find ourselves with another town in nothern Japan, that awaits for the nation system to return.

Benefit to the entire server:
It will allow an easier expansion of Towns and less rivalry for close territories. While other solution can be explored to limit one player towns.

Effect on game balance:
It should affect it if incorporated carelessly, but if it is carefully handled, and the nation cost isn't too high, people can easily be motivated to make their own nation on our near empty map, rather than join already existing one - One way to do so would be to give an incentive to people to make nations. Giving the king bonuses, or other things like that.

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
Even if the nation system returns, we will strongly discourage towns below the town level of 4 (At least 25 people) from starting a nation, as that will end up with nations having towns with only 1-5 people in it. 

If you wish to keep your Imperial Province more exclusive, try using the "plots" and "town rank" features!
Check **/town** for more information.

**Comment by Barbadosian** [comment]
Nations have been re-introduced with siege war functionalities. For details regarding nations and towns please refer to wiki.naturecraft.world.

Thank you for your support in NatureCraft and we always appreciate your feedback.
