### ISSUE TITLE
[Bug] Disappearing Spawner

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#58]
Submitted By:
Iraden

Game Version/Launcher:
1.16.1 Vanilla

Bug Description:
I build a Skelton Spawner farm near coordinates 16394 12 -4182 and it keeps disappearing. I'll be sitting there using the farm then suddenly skeletons stop spawning, I go check and the spawner is gone. I got an admin to help to replace it once but since it has disappeared again.

Type Key:
[BUG]

**Comment by naturecraft-development** [comment]
Unable to reproduce the problem.
