### ISSUE TITLE
[Bug] Repair Costs

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#59]
Submitted By:
Iraden

Game Version/Launcher:
1.16.1 Vanilla

Bug Description:
It seems like the repair costs keep changing seemingly randomly in very short time periods on tools I don't even use, in general, I think the prices are a bit high all around. Repairing a tool is hardly a one-time thing so seeing 13k repair for half-used diamond armor has made me start to kind of ignore the system. 

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
We are working on a better method to repair tools. Should be ready with the release of the custom items and dungeon loot.
