### ISSUE TITLE
[Bug] Random Death in the Nether

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#62]
Submitted By:
Maulvath

Game Version/Launcher:
1.16.3 Vanilla

Bug Description:
I was swimming underneath a reactor in the Nether my dragonborn perk protecting me from damage. I had elytras in my inventory, netherrack, some watermelon and other random blocs when i suddenly died. I was full life and have no clue how it happened.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
I'll come online and help you
