### ISSUE TITLE
[Feature] Sandersnaturecraft

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#63]
Submitted By:
ssanderr

Feature Description:
this server sounds like the old sandersnaturecraft. is there some conection?

Benefit to the entire server:
didn't know how else to ask

Effect on game balance:
No, just wondering :) if you want to contact me go to https://sandersnaturecraft.enjin.com/ 

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
Please do not advertise other servers. Our partners are listed.
