### ISSUE TITLE
[Feature] General suggestons and issues with the Towny plugin

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#64]
Submitted By:
Maulvath

Feature Description:
As we currently stand, the Towny plugin beneficiate greatly - As I have reported beforehand - Small towns to the point where they are almost immortals and will never vanish without Admin's intervention. We have more than one town that will require more than 3000 days to fall to ruin. On a purely opposite side, as reported by the leader of Scotland Jathrowbi and myself, the medium-large towns have a huge problem to develop. I can only give the exemple of Shima, but it cost roughly 1500-2000 for a SINGLE claim. This has in turned switch the server from a place where we can relax, to a place where we spend our days thinking and theorizing on ways to make money, spend hours farming and replanting, while our redstone guy works on an effective automated farm, which in turn damper his will to play. This entire problem can of course be fixed with a lower of the costs, but I think as well that the problem really comes from the lack of Nations. The words of the administrative team has been that you wished for nations to be formed only whence a town reach approximately 25 players...This is a very bad idea. Not only will it immediatly create super-powers that will regardless assimilate towns of one players, because why wouldn't they; Ergo removing the entire point behind Nation removal, but it will also completely remove to new ambitious towns to ever rival with the big players who could simply decide to declare war on small towns to assimilate them without much trouble. A protection would, on the other hand, remove any form of interesting geo-politic on the server, while wars being fought exclusively in between  large nations, will just remove war alltogether. As a result, I suggest that Nations are enabled to be formed again, with a reduced cost, and a base limit of town per nations

Benefit to the entire server:
The solution offers a simple possibility for Nations to exist without 1 people towns forming them. if we assume that every nation can create as a base 4 Towns, increasing then by 1 every 15 persons in the Nation, the 4 Towns will have no choice but to develop and eventually spread further in an organic way. Likewise the Nation systems having a REDUCED cost, means that new players can more easily form nations, their funds can more easily go to zero due to upkeep. It would encourage new players to play more, and remove their territory if they do not. On the opposite side, larger towns will finally breath and enjoy the game without thinking 'MONEY'. 

Effect on game balance:
Let me put it simply - As of the current day, Shima already uses a nation system; as a single town would have otherwise led us to entirely collapse due to conflicts with other players. We have already assimilated Two players in a de-facto position of town majors simply because they, as well as ourselves, prefered to base separately, while still working over a larger goal, in the empire. As a result, Shima has stretched its borders thin, the upkeep is high, and neither players can expand without considerable efforts every day. I am sure that Jathrowbi would be able to add even more reason why the nation benefits far outweight their removal. 

Beyond it, the current system also has a huge flaw in its assumption that it is going to be "big." While I do see the server eventually growing due to its competent staff, novel ideas, and lack of pay to win elements, it will not reach a 25+ per large town in a very long time. The only possibilities for Towns to reach this level as we are is to blindly recruit, fully knowing that most players become inactive, Scotland, the only nation with that ammount of people within, Has multiple people that I have never seen once connect. Rather than balance the system on what the server would be, it may be better to balance on what it is currently. Changes can come later on.

Finally, the lack of Nation affects the various playstyles that are offered by the Towny plugin. Shima has for instance, the intention to replicate partly the Japanese Feodal system with semi-independant towns that answer the Emperor in time of war, and cooperate for large nation-wide projects. I am sure that other nations have similar goals. For instance, solo players could band together in a group of 1 person bases, which are allied in protection of each other in a disparate network. They would still be disadventaged whence faced with 20+ people towns, but people wishing for that playstyle, will not be crushed under large nations simply due to the adventages given to numbers. Leagues of cities, united kingdoms, many other systems and style of government that player can adopt, are simply not possible in a system that only enable large nations. Large nations with 4 towns of 20+ people? Sure. I'd love that too, but that's absolutely impossible. Not only would the server never sustain three to four nations of 20+ people that are regularly connected, but it will maybe take months, or years, to reach this level.

In the meantime though? Scotland, Shima and any other Town that will raise to a similar level of development and specific political or land ambitions, will be stuck in a grind for money and players, that only lower the fun of players, and force nations to accept people without filter, at the risk to find griefers, people who do not care about the ideas of the Town, or who may become inactive. Some Towns should be able to survive without blindly recruiting, some towns should be able to organize say, interviews for players on voice, or request specific things such as an interview, or a minecraft resume - In other words, it needs to be organic. New players shouldn't be a "Race" to obtain as large numbers as possible into towns, Rather new players should be encouraged to make their own choice, with benefits both in joining a nation, or creating one. 

Thank you for reading, of course this is only my opinion here, and I have no intention to give up on the server, but I admit that I slowly grow tired of being unable to access the Nations benefits, and to be stuck in an endless grind for money that tax my will to play the game.

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
Nation will come with the bungee release.

**Comment by naturecraft-development** [comment]
Thank you for your thoughtful comment. A lot of your ideas have been incorporated. More will be coming with the finalization of the stable rc-1 update!
