### ISSUE TITLE
[Feature] Be able to toggle speed as wood elf.

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#66]
Submitted By:
Retnuh_Ancrest

Feature Description:
I would like to make it so that as wood elf you can put a command or do something so that you speed is turned off.

Benefit to the entire server:
From my experience speed is very annoying when trying to navigate a building, go up ladders ad stuff like that. If you make it togglable that will eliminate the problem.

Effect on game balance:
It will not affect game balance because wood elf will still be able to use speed it will just be toggleable.

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
Although it is annoying, it is not possible with the nature of races to toggle/stop at will.
