### ISSUE TITLE
[Bug] Loki Instant-Break Netherite

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#69]
Submitted By:
Maulvath

Game Version/Launcher:
1.16.3

Bug Description:
During the fight against loki the 12/10/2020 at 9est, Loki has been able to break entire sets of unbreaking Netherites, it has happened not only for me, but as well for Jathrowbi. I am unsure if it is intended or not, but if it isn't...I must suggest that either Loki's drop are drastically increased, or that the feature is removed; it is generally anti-fun and can immediatly force someone out of the fight. If it is a bug, It would be greatly appreciated to be able to recover the lost items

Type Key:
[BUG]

**Comment by naturecraft-development** [comment]
Loki Deprecated.
