### ISSUE TITLE
[Bug] Loki Fight Issues W/ Video

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#70]
Submitted By:
3WM

Game Version/Launcher:
Most Recent

Bug Description:
Multiple Things:
1. While fighting the boss multiple people's armor instantly broke and they lost it people i know are Jathrowbi and Barret (Barret got his stuff back, Jathrowbi did not)
2.Also while fighting, I have a video of me getting kicked for "Fast Heal Hacks" (https://youtu.be/TCH-2U7lAYU)which wasn't the case of course, Barret also got kicked for the same reason while in combat and he lost his gear (which he got back)
3.After Fight, The loot wasn't good at all for the fight, the fight took a while even with like 6+ people there, I didn't recieve any sort of reward for fighting him, and doing a lot of the damage.
4.Things to be added, maybe for a big boss fight, damage should be a key factor in rewards, and also incase of a full inventory set a command like /rewards that will open a inventory with the loot of the battle.

Type Key:
[BUG]

**Comment by naturecraft-development** [comment]
Loki Deprecated.
