### ISSUE TITLE
[Bug] Disappearing Spawner

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#71]
Submitted By:
Iraden

Game Version/Launcher:
1.16.1

Bug Description:
Our spawner has disappeared yet again, this time it lasted much longer but it literally disappeared in the middle of me using the farm and I didn't see any player name enter the farm. 1638 15  -4182 for the location of the farm.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
umm that took me to the middle of some rocks.... under the ocean. Could you post the correct coordinates?
