### ISSUE TITLE
[Feature] General Suggestions about the upcoming reset of claims

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#72]
Submitted By:
Maulvath

Feature Description:
Rather than one, it is multiple suggestions. First, there is obviously a need to make a rule announced clearly in game and in discord, that using the reset to claim existing town territories is illegal, second that a form is created to list towns who ask for the staff help in claiming their territories, avoiding that people who cannot be here during reset, can have their towns put in safezone until they can come on and reclaim it. Third, an in game announcement every two hour until reset that announce the upcoming reset, and offers a link to the aformentionned form. Fourth, a list of Features and Requirement for the update, avaliable at least a day before said update. Especially for nations! Shima intends for instance to immediatly switch so as to more easily reclaim our lands, but we need to know how.

Benefit to the entire server:
It will avoid that people leave the server definitely because they lost their hard work during the reset, finding it instead belonging to another town now. 

Effect on game balance:
It won't, by itself but at the very least people will expect and be ready for the new features.

Type Key:
[FEAT]

**Comment by naturecraft-development** [comment]
We ended up not resetting the town claims. Thank you for your suggestion though!
