### ISSUE TITLE
[Bug] Instadeath in End Reaper Fight

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#73]
Submitted By:
Iraden

Game Version/Launcher:
1.16.1

Bug Description:
Everyone in a while (every 3rd - 4th time on average) when the end reaper spawns I instantly die, no change in armor or buffs to the other runs where he could hardly lower my health so I do think somethings bugging. It seems to happen either the moment the timer ticks down or the first time the end reaper teleports to you. Since dying wipes buffs it can cost a few runs.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
End Reaper has been taken down since operation-stable. We are working on a better dungeons system.
