### ISSUE TITLE
[Bug] I was kicked when riding a strider.

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#80]
Submitted By:
Noobie_White

Game Version/Launcher:
1.16.3 , forge launcher

Bug Description:
When I was riding a strider , I was kicked to the lobby. Reason:"You are sending too many packets, :("

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
Should be fixed by the end of the day. We apologize for the inconvenience!
