### ISSUE TITLE
[Bug] towny bug 

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#82]
Submitted By:
Noobie_White

Game Version/Launcher:
1.16.3 , forge launcher

Bug Description:
Players can get many ancient debris or other blocks with this bug.
If some blocks that were placed before the land is claimed and then players destroy it after the land is claimed , it will be recovery after the town is unclaimed

video : https://youtu.be/w7vxDFj0Rrg
The iron ores in the video are  irrelevant to the bug.

Type Key:
[BUG]

**Comment by benevolent2012** [comment]
The issue should be fixed; regeneration of ores have been disabled. Thanks for raising the issue! If it persists, feel free to open it again :)
