### ISSUE TITLE
[Bug] Minecarts moving ridiculously fast

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#83]
Submitted By:
TriCobaltGaming

Game Version/Launcher:
1.16.3 Vanilla + Optifine

Bug Description:
The minecarts on our supersmelter still work as intended, but move incredibly fast (I assume this is a side effect of the intercontinental railroad, but yeah)

Type Key:
[BUG]

**Comment by Barbadosian** [comment]
This has been reproduced by server dev. We are investigating into the issue.

**Comment by naturecraft-development** [comment]
Should have been fixed by @Barbadosian .
