### ISSUE TITLE
[Feature] Improvement items

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#85]
Submitted By:
Xx_XDeadEyeX_xX

Feature Description:
This feature could improve some of the items already existing on the server, for example: Fallen Dragon's Wings, the materials for these wings could be obtained from a dungeon. These wings fly faster and have more durability. The other is: Netherite Trident, as the name suggests, using the forge, you could make your trident a netherite one. The trident would have more durability and deal more damage. 

Benefit to the entire server:
It would make transportation faster if you want to fly for short distances that doesn't require the railway system, and the Netherite Trident would just make it a stronger trident.

Effect on game balance:
It wouldn't effect much, other then the damage it has and how fast it can fly. The extra damage would be the only thing that could have a bigger effect on the balance then speed.

Type Key:
[FEAT]

**Comment by naturecraft-development** [comment]
Mojang doesn't allow the flexible modifcation of elytras and tridents. Also, those would be flagged as "cheating" by the anticheat, since it is flying beyond the normal fly limit. If we modify this, this will bring about more issues with hackers.
