### ISSUE TITLE
[Feature] Town Banners

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#86]
Submitted By:
AlexShows08

Feature Description:
A way to set a town banner by using a banner maker. People would be able to see it on the map, and it can be duplicated using a blank banner and a small amount of money.

Benefit to the entire server:
It is an easier way to mark towns on the map website and a way to represent towns in server-wide events without having to go to the town directly.

Effect on game balance:
It's less of a game balance feature and more of a cool thing to add, so no it will not affect game balance.

Type Key:
[FEAT]

**Comment by benevolent2012** [comment]
This sounds really cool! We'll look into the banner feature!

We are planning to implement colored town territory (on the map) and other ways to distinguish towns at the moment.
