### ISSUE TITLE
[Feature] Enchanting at spawn

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#91]
Submitted By:
Korvath

Feature Description:
given i had looked at Old Hub and found a fully operation and open enchanting station there i was thinking it could be added to the new spawn

Benefit to the entire server:
it will give player that don't have access to enchanting the means to do so

Effect on game balance:
It would give everyone an even chance to enchant there gear while they still have to supply there own lapis and materials to do the enchant. all that need to be deployed is and enchanting table and 15 book cases for max level enchantments. the player themselves must supply the lapis, gear they wish to enchant and the levels themselves.

Type Key:
[FEAT]

**Comment by naturecraft-development** [comment]
Those will be handled individually by towns.
