### ISSUE TITLE
[Feature] Inventory Tweaks

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#92]
Submitted By:
heartofvirgo94

Feature Description:
Where you can hold your mouse button to quickly put stuff in a chest or your inventory.

Benefit to the entire server:
It will help putting stuff in chests and inventory also help with sorting easyer.

Effect on game balance:
No it will not, all it will do is make it easyer for members of the server sort and put stuff in chests and inventory alot easyer.

Type Key:
[FEAT]

**Comment by Barbadosian** [comment]
Sounds like a good QOL idea. Will review and update.

**Comment by benevolent2012** [comment]
More client mod-side than server side.
