### ISSUE TITLE
[Feature] Vehicles!

### ISSUE THREAD

**Issue by Barbadosian** [naturecraft-dev/naturecraft#93]
Submitted By:
Old nick: VelvetCrow/New Nick: LunaFoxtar

Feature Description:
Add an vehicles plugin without using resourcepack

Benefit to the entire server:
Travel on the world with planes, cars, bikes,etc...could work very good with towny

Effect on game balance:
Just affect on the travel experience, making it more funny, each vehicle need coal to drive if i remember the plugin

Type Key:
[FEAT]

**Comment by Barbadosian** [comment]
This feature is already in server roadmap and will be implemented in the future.

**Comment by Barbadosian** [comment]
Addendum link to suggested plugin https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

**Comment by benevolent2012** [comment]
For Solaris(modern Towny), coming Q2 2021. Will not be for Terra. Don't see the point in "not" having texture pack, since we'll have the same master back for all servers, but will consider if no other alternatives are available. Thank you.
